export const COMMANDCODE_PLAN_CONFIG = {
  values: ["go", "pro", "max"],
  default: "go",
  maxOnlyPrefixes: ["claude-opus-", "claude-fable-"],
  maxOnlyModels: ["sakana/fugu-ultra"],
};

export default {
  id: "commandcode",
  priority: 100,
  alias: "commandcode",
  aliases: [
    "cmc",
  ],
  uiAlias: "cmc",
  display: {
    name: "Command Code",
    icon: "smart_toy",
    color: "#000000",
    textIcon: "CC",
    website: "https://commandcode.ai",
    notice: {
      text: "Use your CommandCode CLI API key (starts with user_...) from ~/.commandcode/auth.json or commandcode.ai/studio.",
      apiKeyUrl: "https://commandcode.ai/studio",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.commandcode.ai/alpha/generate",
    modelsUrl: "https://api.commandcode.ai/provider/v1/models",
    format: "commandcode",
    thinkingFormat: "commandcode",
    forceStream: true,
    headers: {
      "x-command-code-version": "0.25.7",
      "x-cli-environment": "cli",
    },
    tlsFingerprint: {
      browser: "chrome_124",
      os: "macos",
    },
  },
  models: [
    { id: "poolside/laguna-s-2.1-free", name: "Laguna S 2.1" },
    { id: "tencent/hy3-paid", name: "Tencent Hy3" },
    { id: "tencent/hy4-preview", name: "Tencent Hy4 Preview" },
    { id: "moonshotai/Kimi-K3", name: "Kimi K3" },
    { id: "moonshotai/Kimi-K2.7-Code", name: "Kimi K2.7 Code" },
    { id: "moonshotai/Kimi-K2.7-Code-Highspeed", name: "Kimi K2.7 Code HighSpeed" },
    { id: "moonshotai/Kimi-K2.6", name: "Kimi K2.6" },
    { id: "moonshotai/Kimi-K2.5", name: "Kimi K2.5" },
    { id: "zai-org/GLM-5.3", name: "GLM-5.3" },
    { id: "z-ai/glm-5.3-flash", name: "GLM-5.3 Flash" },
    { id: "zai-org/GLM-5.2", name: "GLM-5.2" },
    { id: "zai-org/GLM-5.2-Fast", name: "GLM-5.2 Fast" },
    { id: "zai-org/GLM-5.1", name: "GLM-5.1" },
    { id: "zai-org/GLM-5", name: "GLM-5" },
    { id: "MiniMaxAI/MiniMax-M3", name: "MiniMax M3" },
    { id: "MiniMaxAI/MiniMax-M2.7", name: "MiniMax M2.7" },
    { id: "MiniMaxAI/MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek/deepseek-v4-flash-fast", name: "DeepSeek V4 Flash Fast" },
    { id: "deepseek/deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision" },
    { id: "Qwen/Qwen3.8-Max", name: "Qwen 3.8 Max" },
    { id: "Qwen/Qwen3.8-27B", name: "Qwen 3.8 27B" },
    { id: "Qwen/Qwen3.8-Flash", name: "Qwen 3.8 Flash" },
    { id: "Qwen/Qwen3.6-Max-Preview", name: "Qwen 3.6 Max Preview" },
    { id: "Qwen/Qwen3.6-Plus", name: "Qwen 3.6 Plus" },
    { id: "Qwen/Qwen3.7-Max", name: "Qwen 3.7 Max" },
    { id: "Qwen/Qwen3.7-Plus", name: "Qwen 3.7 Plus" },
    { id: "Qwen/Qwen3.7-Flash", name: "Qwen 3.7 Flash" },
    { id: "stepfun/Step-3.7-Flash", name: "Step 3.7 Flash" },
    { id: "stepfun/Step-3.5-Flash", name: "Step 3.5 Flash" },
    { id: "xiaomi/mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "xiaomi/mimo-v2.5", name: "MiMo V2.5" },
    { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "meta/muse-spark-1.2-contributor", name: "Muse Spark 1.2 Contributor" },
    { id: "xai/grok-4.5", name: "Grok 4.5" },
    { id: "thinkingmachines/inkling", name: "Inkling" },
    { id: "thinkingmachines/inkling-small", name: "Inkling Small" },
  ],
};
